### ISSUE TITLE
Error : after the second argument: expected table, got nil   

### ISSUE THREAD

**Issue by LamprosPitsillos** [debugloop/telescope-undo.nvim#41]
```error
Error executing Lua callback: vim/shared.lua:0: after the second argument: expected table, got nil                                                                                              
stack traceback:                                                                                                                                                                                
        [C]: in function 'error'                                                                                                                                                                
        vim/shared.lua: in function 'validate'                                                                                                                                                  
        vim/shared.lua: in function 'tbl_deep_extend'                                                                                                                                           
        ...y/telescope-undo.nvim/lua/telescope/_extensions/undo.lua:37: in function <...y/telescope-undo.nvim/lua/telescope/_extensions/undo.lua:36>                                            
        ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:193: in function 'run_command'                                                                                              
        ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:259: in function 'load_command'                                                                                             
        ...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:108: in function <...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:107>      
```
The entire Telescope conf: https://github.com/LamprosPitsillos/nixos-config/blob/main/home-manager/programs/nvim/lua/plugins/Telescope.lua
A snipet: 
```lua
                extensions = {
                    undo = {
                        use_delta = false,
                        use_custom_command = nil, -- setting this implies `use_delta = false`. Accepted format is: { "bash", "-c", "echo '$DIFF' | delta" }
                        side_by_side = false,
                        layout_strategy = "vertical",
                        layout_config = {
                            preview_height = 0.8,
                        },
                        diff_context_lines = vim.o.scrolloff,
                        entry_format = "state #$ID, $STAT, $TIME",
                        time_format = "",
                        mappings = {
                            i = {
                                -- IMPORTANT: Note that telescope-undo must be available when telescope is configured if
                                -- you want to replicate these defaults and use the following actions. This means
                                -- installing as a dependency of telescope in it's `requirements` and loading this
                                -- extension from there instead of having the separate plugin definition as outlined
                                -- above.
                                ["<cr>"] = require("telescope-undo.actions").yank_additions,
                                ["<S-cr>"] = require("telescope-undo.actions").yank_deletions,
                                ["<C-cr>"] = require("telescope-undo.actions").restore,
                            },
                        },
                    },
                    ast_grep = {
                        command = {
                        ......

```

**Comment by debugloop** [comment]
Are you on the latest version? I fixed very similar error with the latest commit, that bug was in the latest version for only a few hours. In case this is a different thing (on my phone, can't check details right now) and you are on the latest version, please additionally provide how you invoked telescope-undo.

**Comment by debugloop** [comment]
Yup, that's fixed on the latest version afaict from what you provided :+1:

**Comment by LamprosPitsillos** [comment]
Sorry but for me it's still an issue.
On the latest commit.
> additionally provide how you invoked telescope-undo.

I invoke it using `Telescope undo`


![image](https://github.com/debugloop/telescope-undo.nvim/assets/61395246/726bc0c2-d8a0-44eb-bc2f-f24ae3838760)

**Comment by debugloop** [comment]
It's not reproducible with a minimal config, this has to be something about your setup somewhere. I suggest you clear your cache/data dirs and rebootstrap that using your config, you probably somehow pulled in the bad version (sorry for having published that one for a few hours 💔). No idea why Lazy would show the current commit though 🤔 If it still fails after rebootstrapping, please make this minimal config break, let me know, and I'll take a look:

```lua
-- bend paths for this repro
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- plugin specs
local plugins = {
  {
    "debugloop/telescope-undo.nvim",
    lazy = true,
    dependencies = {
      {
        "nvim-telescope/telescope.nvim",
        dependencies = { "nvim-lua/plenary.nvim" },
      },
    },
    keys = {
      {
        "<leader>u",
        "<cmd>Telescope undo<cr>",
        desc = "undo history",
      },
    },
    opts = {
      extensions = {
        undo = {},
      },
    },
    config = function(_, opts)
      require("telescope").setup(opts)
      require("telescope").load_extension("undo")
    end,
  },
}

-- let's go
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

Test using `nvim -u repro.lua testfile`, make a quick undoable edit, and `\u` (default leader) or use the lua invoke you posted. Go from there, substitute your config for `telescope(-undo)?`, then add whatever else you might need to make it break, I'll have a look then 👍🏻

Best of luck finding the bad circumstances quickly 🍀

**Comment by LamprosPitsillos** [comment]
Lazy is showing the correct commit , navigating in to the file shows that the plugin is indeed at the latest commit.
I forked , and used my own fork from dir using lazy and tried to figure out why this is happening...

```lua 
M.exports.undo = function(config)
vim.notify(vim.inspect(M.config))
vim.notify(vim.inspect(M))
vim.notify(vim.inspect(config))
  config = vim.tbl_deep_extend("force", M.config, config or {})
  if config.theme then
    config = require("telescope.themes")["get_" .. config.theme](config)
  end
  require("telescope-undo").undo(config)
end

M.setup = function(extension_config, telescope_config)

  M.config = vim.tbl_deep_extend("force", defaults, extension_config)
    vim.notify("config set")
    vim.notify(vim.inspect(M.config))
  if M.config["side_by_side"] and not M.config["use_delta"] then
    error("telescope_undo.nvim: setting side_by_side but not use_delta will have no effect")
  end
end

return telescope.register_extension(M)
```

```
2023-11-16T00:19:41  INFO config set                                                                                                                                                        
2023-11-16T00:19:41  INFO {                                                                                                                                                                 
  diff_context_lines = 0,                                                                                                                                                                    
  entry_format = "state #$ID, $STAT, $TIME",                                                                                                                                                 
  layout_config = {                                                                                                                                                                          
    preview_height = 0.8                                                                                                                                                                     
  },                                                                                                                                                                                         
  layout_strategy = "vertical",                                                                                                                                                              
  mappings = {                                                                                                                                                                               
    i = {                                                                                                                                                                                    
      ["<C-cr>"] = <function 1>,                                                                                                                                                             
      ["<C-r>"] = <function 1>,                                                                                                                                                              
      ["<C-y>"] = <function 2>,                                                                                                                                                              
      ["<S-cr>"] = <function 2>,                                                                                                                                                             
      ["<cr>"] = <function 3>                                                                                                                                                                
    },                                                                                                                                                                                       
    n = {                                                                                                                                                                                    
      Y = <function 2>,                                                                                                                                                                      
      u = <function 1>,                                                                                                                                                                      
      y = <function 3>                                                                                                                                                                       
    }                                                                                                                                                                                        
  },                                                                                                                                                                                         
  saved_only = false,                                                                                                                                                                        
  side_by_side = false,                                                                                                                                                                      
  time_format = "",                                                                                                                                                                          
  use_delta = false                                                                                                                                                                          
}                                                                                                                                                                                            
2023-11-16T00:19:41  INFO config set                                                                                                                                                        
2023-11-16T00:19:41  INFO {                                                                                                                                                                 
  diff_context_lines = 0,                                                                                                                                                                    
  entry_format = "state #$ID, $STAT, $TIME",                                                                                                                                                 
  layout_config = {                                                                                                                                                                          
    preview_height = 0.8                                                                                                                                                                     
  },                                                                                                                                                                                         
  layout_strategy = "vertical",                                                                                                                                                              
  mappings = {                                                                                                                                                                               
    i = {                                                                                                                                                                                    
      ["<C-cr>"] = <function 1>,                                                                                                                                                             
      ["<C-r>"] = <function 1>,                                                                                                                                                              
      ["<C-y>"] = <function 2>,                                                                                                                                                              
      ["<S-cr>"] = <function 2>,                                                                                                                                                             
      ["<cr>"] = <function 3>                                                                                                                                                                
    },                                                                                                                                                                                       
    n = {                                                                                                                                                                                    
      Y = <function 2>,                                                                                                                                                                      
      u = <function 1>,                   
      y = <function 3>                                                                                                                                                                       
    }                                                                                                                                                                                        
  },                                                                                                                                                                                         
  saved_only = false,                                                                                                                                                                        
  side_by_side = false,                                                                                                                                                                      
  time_format = "",                                                                                                                                                                          
  use_delta = false                                                                                                                                                                          
}                            
////// After calling `Telescope undo`                                                                                                                                                                
2023-11-16T00:20:02  INFO nil                                                                                                                                                               
2023-11-16T00:20:02  INFO {                                                                                                                                                                 
  formatter = <function 1>,                                                                                                                                                                  
  setup = <function 2>                                                                                                                                                                       
}                                                                                                                                                                                            
2023-11-16T00:20:02  INFO {}                                                                                                                                                                
```
Thanks for your efforts any way , i will try and investigate some more and notify back with a pr if i find anything.
